//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.SMSPanel.KashanSMSReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagesBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessagesBL : Messenger.SMSPanel.KashanSMSReference.BaseBL {
        
        private long MsgIDField;
        
        private int UserIDField;
        
        private int LinkIDField;
        
        private int NumberIDField;
        
        private byte MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdhField;
        
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        private int FirstLocationField;
        
        private int CurrentLocationField;
        
        private int PartsField;
        
        private bool IsFlashField;
        
        private bool IsReadField;
        
        private bool IsUnicodeField;
        
        private double CreditField;
        
        private int ModuleField;
        
        private int RecCountField;
        
        private int RecFailedField;
        
        private int RecSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MsgID {
            get {
                return this.MsgIDField;
            }
            set {
                if ((this.MsgIDField.Equals(value) != true)) {
                    this.MsgIDField = value;
                    this.RaisePropertyChanged("MsgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int LinkID {
            get {
                return this.LinkIDField;
            }
            set {
                if ((this.LinkIDField.Equals(value) != true)) {
                    this.LinkIDField = value;
                    this.RaisePropertyChanged("LinkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumberID {
            get {
                return this.NumberIDField;
            }
            set {
                if ((this.NumberIDField.Equals(value) != true)) {
                    this.NumberIDField = value;
                    this.RaisePropertyChanged("NumberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public byte MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((this.MsgTypeField.Equals(value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Udh {
            get {
                return this.UdhField;
            }
            set {
                if ((object.ReferenceEquals(this.UdhField, value) != true)) {
                    this.UdhField = value;
                    this.RaisePropertyChanged("Udh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int FirstLocation {
            get {
                return this.FirstLocationField;
            }
            set {
                if ((this.FirstLocationField.Equals(value) != true)) {
                    this.FirstLocationField = value;
                    this.RaisePropertyChanged("FirstLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((this.CurrentLocationField.Equals(value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((this.PartsField.Equals(value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool IsFlash {
            get {
                return this.IsFlashField;
            }
            set {
                if ((this.IsFlashField.Equals(value) != true)) {
                    this.IsFlashField = value;
                    this.RaisePropertyChanged("IsFlash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((this.IsUnicodeField.Equals(value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int RecCount {
            get {
                return this.RecCountField;
            }
            set {
                if ((this.RecCountField.Equals(value) != true)) {
                    this.RecCountField = value;
                    this.RaisePropertyChanged("RecCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int RecFailed {
            get {
                return this.RecFailedField;
            }
            set {
                if ((this.RecFailedField.Equals(value) != true)) {
                    this.RecFailedField = value;
                    this.RaisePropertyChanged("RecFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int RecSuccess {
            get {
                return this.RecSuccessField;
            }
            set {
                if ((this.RecSuccessField.Equals(value) != true)) {
                    this.RecSuccessField = value;
                    this.RaisePropertyChanged("RecSuccess");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Messenger.SMSPanel.KashanSMSReference.MessagesBL))]
    public partial class BaseBL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodType", Namespace="http://tempuri.org/")]
    public enum PeriodType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Once = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yearly = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KashanSMSReference.SendSoap")]
    public interface SendSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.GetCreditResponse GetCredit(Messenger.SMSPanel.KashanSMSReference.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetCreditResponse> GetCreditAsync(Messenger.SMSPanel.KashanSMSReference.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        byte GetDelivery(long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<byte> GetDeliveryAsync(long recId);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDelivery", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponse UpdateDelivery(Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponse> UpdateDeliveryAsync(Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponse GetInboxCount(Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponse> GetInboxCountAsync(Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.GetMessagesResponse GetMessages(Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetMessagesResponse> GetMessagesAsync(Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleSms", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponse ScheduleSms(Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponse> ScheduleSmsAsync(Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.SendSmsResponse SendSms(Messenger.SMSPanel.KashanSMSReference.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.SendSmsResponse> SendSmsAsync(Messenger.SMSPanel.KashanSMSReference.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsStringRec", ReplyAction="*")]
        Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponse SendSmsStringRec(Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsStringRec", ReplyAction="*")]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponse> SendSmsStringRecAsync(Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.GetCreditRequestBody Body;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(Messenger.SMSPanel.KashanSMSReference.GetCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody() {
        }
        
        public GetCreditRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.GetCreditResponseBody Body;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(Messenger.SMSPanel.KashanSMSReference.GetCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody() {
        }
        
        public GetCreditResponseBody(double GetCreditResult) {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDelivery", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequestBody Body;
        
        public UpdateDeliveryRequest() {
        }
        
        public UpdateDeliveryRequest(Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RecID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public UpdateDeliveryRequestBody() {
        }
        
        public UpdateDeliveryRequestBody(long RecID, string username, string password) {
            this.RecID = RecID;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponseBody Body;
        
        public UpdateDeliveryResponse() {
        }
        
        public UpdateDeliveryResponse(Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateDeliveryResult;
        
        public UpdateDeliveryResponseBody() {
        }
        
        public UpdateDeliveryResponseBody(int UpdateDeliveryResult) {
            this.UpdateDeliveryResult = UpdateDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCount", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequestBody Body;
        
        public GetInboxCountRequest() {
        }
        
        public GetInboxCountRequest(Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isRead;
        
        public GetInboxCountRequestBody() {
        }
        
        public GetInboxCountRequestBody(string username, string password, bool isRead) {
            this.username = username;
            this.password = password;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponseBody Body;
        
        public GetInboxCountResponse() {
        }
        
        public GetInboxCountResponse(Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetInboxCountResult;
        
        public GetInboxCountResponseBody() {
        }
        
        public GetInboxCountResponseBody(int GetInboxCountResult) {
            this.GetInboxCountResult = GetInboxCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(Messenger.SMSPanel.KashanSMSReference.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string username, string password, int location, string from, int index, int count) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(Messenger.SMSPanel.KashanSMSReference.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.MessagesBL[] GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(Messenger.SMSPanel.KashanSMSReference.MessagesBL[] GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScheduleSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScheduleSms", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequestBody Body;
        
        public ScheduleSmsRequest() {
        }
        
        public ScheduleSmsRequest(Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScheduleSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime scheduleDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Messenger.SMSPanel.KashanSMSReference.PeriodType period;
        
        public ScheduleSmsRequestBody() {
        }
        
        public ScheduleSmsRequestBody(string username, string password, string to, string from, string text, bool isflash, System.DateTime scheduleDateTime, Messenger.SMSPanel.KashanSMSReference.PeriodType period) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.scheduleDateTime = scheduleDateTime;
            this.period = period;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScheduleSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScheduleSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponseBody Body;
        
        public ScheduleSmsResponse() {
        }
        
        public ScheduleSmsResponse(Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScheduleSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ScheduleSmsResult;
        
        public ScheduleSmsResponseBody() {
        }
        
        public ScheduleSmsResponseBody(int ScheduleSmsResult) {
            this.ScheduleSmsResult = ScheduleSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(Messenger.SMSPanel.KashanSMSReference.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] status;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string username, string password, Messenger.SMSPanel.KashanSMSReference.ArrayOfString to, string from, string text, bool isflash, string udh, Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(Messenger.SMSPanel.KashanSMSReference.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] status;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(int SendSmsResult, Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, byte[] status) {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsStringRecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsStringRec", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequestBody Body;
        
        public SendSmsStringRecRequest() {
        }
        
        public SendSmsStringRecRequest(Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsStringRecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfString recIdstr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] status;
        
        public SendSmsStringRecRequestBody() {
        }
        
        public SendSmsStringRecRequestBody(string username, string password, Messenger.SMSPanel.KashanSMSReference.ArrayOfString to, string from, string text, bool isflash, string udh, Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, Messenger.SMSPanel.KashanSMSReference.ArrayOfString recIdstr, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.recIdstr = recIdstr;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsStringRecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsStringRecResponse", Namespace="http://tempuri.org/", Order=0)]
        public Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponseBody Body;
        
        public SendSmsStringRecResponse() {
        }
        
        public SendSmsStringRecResponse(Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsStringRecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsStringRecResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Messenger.SMSPanel.KashanSMSReference.ArrayOfString recIdstr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] status;
        
        public SendSmsStringRecResponseBody() {
        }
        
        public SendSmsStringRecResponseBody(int SendSmsStringRecResult, Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, Messenger.SMSPanel.KashanSMSReference.ArrayOfString recIdstr, byte[] status) {
            this.SendSmsStringRecResult = SendSmsStringRecResult;
            this.recId = recId;
            this.recIdstr = recIdstr;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSoapChannel : Messenger.SMSPanel.KashanSMSReference.SendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<Messenger.SMSPanel.KashanSMSReference.SendSoap>, Messenger.SMSPanel.KashanSMSReference.SendSoap {
        
        public SendSoapClient() {
        }
        
        public SendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.GetCreditResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.GetCredit(Messenger.SMSPanel.KashanSMSReference.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public double GetCredit(string username, string password) {
            Messenger.SMSPanel.KashanSMSReference.GetCreditRequest inValue = new Messenger.SMSPanel.KashanSMSReference.GetCreditRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Messenger.SMSPanel.KashanSMSReference.GetCreditResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).GetCredit(inValue);
            return retVal.Body.GetCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetCreditResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.GetCreditAsync(Messenger.SMSPanel.KashanSMSReference.GetCreditRequest request) {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetCreditResponse> GetCreditAsync(string username, string password) {
            Messenger.SMSPanel.KashanSMSReference.GetCreditRequest inValue = new Messenger.SMSPanel.KashanSMSReference.GetCreditRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).GetCreditAsync(inValue);
        }
        
        public byte GetDelivery(long recId) {
            return base.Channel.GetDelivery(recId);
        }
        
        public System.Threading.Tasks.Task<byte> GetDeliveryAsync(long recId) {
            return base.Channel.GetDeliveryAsync(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.UpdateDelivery(Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest request) {
            return base.Channel.UpdateDelivery(request);
        }
        
        public int UpdateDelivery(long RecID, string username, string password) {
            Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest inValue = new Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequestBody();
            inValue.Body.RecID = RecID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).UpdateDelivery(inValue);
            return retVal.Body.UpdateDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.UpdateDeliveryAsync(Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest request) {
            return base.Channel.UpdateDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryResponse> UpdateDeliveryAsync(long RecID, string username, string password) {
            Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest inValue = new Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.UpdateDeliveryRequestBody();
            inValue.Body.RecID = RecID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).UpdateDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.GetInboxCount(Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest request) {
            return base.Channel.GetInboxCount(request);
        }
        
        public int GetInboxCount(string username, string password, bool isRead) {
            Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest inValue = new Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.isRead = isRead;
            Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).GetInboxCount(inValue);
            return retVal.Body.GetInboxCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.GetInboxCountAsync(Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest request) {
            return base.Channel.GetInboxCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetInboxCountResponse> GetInboxCountAsync(string username, string password, bool isRead) {
            Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest inValue = new Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.GetInboxCountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.isRead = isRead;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).GetInboxCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.GetMessagesResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.GetMessages(Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public Messenger.SMSPanel.KashanSMSReference.MessagesBL[] GetMessages(string username, string password, int location, string from, int index, int count) {
            Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest inValue = new Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.GetMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            Messenger.SMSPanel.KashanSMSReference.GetMessagesResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetMessagesResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.GetMessagesAsync(Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest request) {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.GetMessagesResponse> GetMessagesAsync(string username, string password, int location, string from, int index, int count) {
            Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest inValue = new Messenger.SMSPanel.KashanSMSReference.GetMessagesRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.GetMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).GetMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.ScheduleSms(Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest request) {
            return base.Channel.ScheduleSms(request);
        }
        
        public int ScheduleSms(string username, string password, string to, string from, string text, bool isflash, System.DateTime scheduleDateTime, Messenger.SMSPanel.KashanSMSReference.PeriodType period) {
            Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest inValue = new Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.scheduleDateTime = scheduleDateTime;
            inValue.Body.period = period;
            Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).ScheduleSms(inValue);
            return retVal.Body.ScheduleSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.ScheduleSmsAsync(Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest request) {
            return base.Channel.ScheduleSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.ScheduleSmsResponse> ScheduleSmsAsync(string username, string password, string to, string from, string text, bool isflash, System.DateTime scheduleDateTime, Messenger.SMSPanel.KashanSMSReference.PeriodType period) {
            Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest inValue = new Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.ScheduleSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.scheduleDateTime = scheduleDateTime;
            inValue.Body.period = period;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).ScheduleSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.SendSmsResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.SendSms(Messenger.SMSPanel.KashanSMSReference.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public int SendSms(string username, string password, Messenger.SMSPanel.KashanSMSReference.ArrayOfString to, string from, string text, bool isflash, string udh, ref Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, ref byte[] status) {
            Messenger.SMSPanel.KashanSMSReference.SendSmsRequest inValue = new Messenger.SMSPanel.KashanSMSReference.SendSmsRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            Messenger.SMSPanel.KashanSMSReference.SendSmsResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).SendSms(inValue);
            recId = retVal.Body.recId;
            status = retVal.Body.status;
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.SendSmsResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.SendSmsAsync(Messenger.SMSPanel.KashanSMSReference.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.SendSmsResponse> SendSmsAsync(string username, string password, Messenger.SMSPanel.KashanSMSReference.ArrayOfString to, string from, string text, bool isflash, string udh, Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, byte[] status) {
            Messenger.SMSPanel.KashanSMSReference.SendSmsRequest inValue = new Messenger.SMSPanel.KashanSMSReference.SendSmsRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponse Messenger.SMSPanel.KashanSMSReference.SendSoap.SendSmsStringRec(Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest request) {
            return base.Channel.SendSmsStringRec(request);
        }
        
        public int SendSmsStringRec(string username, string password, Messenger.SMSPanel.KashanSMSReference.ArrayOfString to, string from, string text, bool isflash, string udh, ref Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, ref Messenger.SMSPanel.KashanSMSReference.ArrayOfString recIdstr, ref byte[] status) {
            Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest inValue = new Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.recIdstr = recIdstr;
            inValue.Body.status = status;
            Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponse retVal = ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).SendSmsStringRec(inValue);
            recId = retVal.Body.recId;
            recIdstr = retVal.Body.recIdstr;
            status = retVal.Body.status;
            return retVal.Body.SendSmsStringRecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponse> Messenger.SMSPanel.KashanSMSReference.SendSoap.SendSmsStringRecAsync(Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest request) {
            return base.Channel.SendSmsStringRecAsync(request);
        }
        
        public System.Threading.Tasks.Task<Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecResponse> SendSmsStringRecAsync(string username, string password, Messenger.SMSPanel.KashanSMSReference.ArrayOfString to, string from, string text, bool isflash, string udh, Messenger.SMSPanel.KashanSMSReference.ArrayOfLong recId, Messenger.SMSPanel.KashanSMSReference.ArrayOfString recIdstr, byte[] status) {
            Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest inValue = new Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequest();
            inValue.Body = new Messenger.SMSPanel.KashanSMSReference.SendSmsStringRecRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.recIdstr = recIdstr;
            inValue.Body.status = status;
            return ((Messenger.SMSPanel.KashanSMSReference.SendSoap)(this)).SendSmsStringRecAsync(inValue);
        }
    }
}
