//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mesCompany()
        {
            this.mesMessages = new HashSet<mesMessage>();
        }
    
        public int pkfCompany { get; set; }
        public string companyName { get; set; }
        public Nullable<int> serialIdCompany { get; set; }
        public bool active { get; set; }
        public byte[] pic { get; set; }
        public string picName { get; set; }
        public string pass { get; set; }
        public string userName { get; set; }
        public System.DateTime changeDateEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesMessage> mesMessages { get; set; }
    }
}
