//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mesDocument()
        {
            this.mesMessages = new HashSet<mesMessage>();
        }
    
        public int pkfDocument { get; set; }
        public int FkfMessage { get; set; }
        public int FkfDocumentType { get; set; }
        public byte[] fileScan { get; set; }
        public string memo { get; set; }
        public string fileExt { get; set; }
        public Nullable<int> fileSize { get; set; }
    
        public virtual mesDocumentType mesDocumentType { get; set; }
        public virtual mesMessage mesMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesMessage> mesMessages { get; set; }
    }
}
