//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesLogin
    {
        public int pkfLogin { get; set; }
        public string idConnectionSignalR { get; set; }
        public int FkfUser { get; set; }
        public int loginType { get; set; }
        public System.DateTime connectDateTime { get; set; }
        public Nullable<System.DateTime> disconnectDateTime { get; set; }
        public string comment { get; set; }
        public string ip { get; set; }
        public int appVersion { get; set; }
        public string androidVersion { get; set; }
        public string mobileName { get; set; }
    
        public virtual mesUser mesUser { get; set; }
    }
}
