//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesPanel
    {
        public int pkfPanel { get; set; }
        public string PanelName { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string Sender { get; set; }
    }
}
