//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesSetting
    {
        public int pkfSetting { get; set; }
        public Nullable<bool> SendEmailManageEnable { get; set; }
        public string SendEmailManageHost { get; set; }
        public Nullable<int> SendEmailManagePort { get; set; }
        public string SendEmailManageUsername { get; set; }
        public string SendEmailManageUserPass { get; set; }
        public string SendEmailManageFrom { get; set; }
        public string SendEmailManageTo { get; set; }
        public Nullable<bool> RegistrationFormVisit { get; set; }
        public string ContactsInvitationText { get; set; }
        public Nullable<bool> ShowHelpForm { get; set; }
        public string HelpMainUrl { get; set; }
        public int ShowNotificationRepeat { get; set; }
        public Nullable<int> InvitationPanelID { get; set; }
        public string MessageInstallInvitation { get; set; }
        public Nullable<int> InstallInvitationPanelID { get; set; }
        public string NumberSMSAddUser { get; set; }
        public string NumberSMSUpdateUser { get; set; }
        public Nullable<int> NumberSMSManagerPanelID { get; set; }
        public string NumberSMSManagerText { get; set; }
        public string serverKeyFireBase { get; set; }
        public string senderIdFireBase { get; set; }
        public string webAddr { get; set; }
    }
}
