//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesStatusMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mesStatusMessage()
        {
            this.mesMessages = new HashSet<mesMessage>();
        }
    
        public int pkfStatusMessage { get; set; }
        public string statusMessage { get; set; }
        public string statusMessageCode { get; set; }
        public string memo { get; set; }
        public System.DateTime changeDateEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesMessage> mesMessages { get; set; }
    }
}
