//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mesUser()
        {
            this.mesLogins = new HashSet<mesLogin>();
            this.mesMessages = new HashSet<mesMessage>();
        }
    
        public int pkfUser { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public string famile { get; set; }
        public byte[] pic { get; set; }
        public string picName { get; set; }
        public string pass { get; set; }
        public string userName { get; set; }
        public Nullable<int> ActiveCode { get; set; }
        public Nullable<bool> UserActive { get; set; }
        public Nullable<System.DateTime> UserCreateDate { get; set; }
        public Nullable<System.DateTime> UserExpireDate { get; set; }
        public Nullable<bool> DeactiveAdministrator { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public string PrivateKeyRefresh { get; set; }
        public Nullable<System.DateTime> PrivateKeyExpire { get; set; }
        public string tokenFireBase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesLogin> mesLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesMessage> mesMessages { get; set; }
    }
}
