//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesVersioning
    {
        public int pkfVersioning { get; set; }
        public int VersionCode { get; set; }
        public string VersionName { get; set; }
        public bool ForceInstalling { get; set; }
        public string VersionDescription { get; set; }
    }
}
